//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pildipank_ver2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int PictureId { get; set; }
        public string CommenterId { get; set; }
        public System.DateTime Created { get; set; }
        public string Comment1 { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Picture Picture { get; set; }
    }
}
